import type { Testimonial } from "@/types";

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sana Mehmood",
    city: "Lahore",
    rating: 5,
    text: "The Classic Noir Abaya is absolutely breathtaking! The quality of the fabric is unmatched and the gold embroidery detail is even more beautiful in person. I wore it to my cousin's wedding and received so many compliments. RIWAYAH is truly a luxury brand!",
    productBought: "Classic Noir Abaya",
    avatar: "/testimonials/avatar-1.jpg",
    verified: true,
  },
  {
    id: "t2",
    name: "Fatima Khurram",
    city: "Karachi",
    rating: 5,
    text: "Ordered the Royal Zahra Kaftan for Eid and I am completely in love. The zardozi work is so intricate and the delivery was super fast. The packaging was also premium — felt like receiving a gift! Will definitely order again.",
    productBought: "Royal Zahra Kaftan",
    avatar: "/testimonials/avatar-2.jpg",
    verified: true,
  },
  {
    id: "t3",
    name: "Zara Hussain",
    city: "Islamabad",
    rating: 5,
    text: "The Pearl Embroidered Dupatta is a dream! So light and delicate. I paired it with my bridal lehenga and it elevated the entire look. The pearls are securely stitched, nothing fell off even after wearing it all night.",
    productBought: "Pearl Embroidered Dupatta",
    avatar: "/testimonials/avatar-3.jpg",
    verified: true,
  },
  {
    id: "t4",
    name: "Hira Awan",
    city: "Faisalabad",
    rating: 4,
    text: "Great quality abaya, fits true to size. Customer support was very responsive when I had a sizing question. Shipping was a bit delayed but the product was absolutely worth the wait. Highly recommend RIWAYAH!",
    productBought: "Classic Noir Abaya",
    avatar: "/testimonials/avatar-4.jpg",
    verified: true,
  },
  {
    id: "t5",
    name: "Aisha Tariq",
    city: "Multan",
    rating: 5,
    text: "I was hesitant to buy online but the 3D preview feature made me so confident! I could literally see how the kaftan looks from every angle before ordering. This is the future of online shopping. Amazing experience!",
    productBought: "Royal Zahra Kaftan",
    avatar: "/testimonials/avatar-5.jpg",
    verified: true,
  },
];
